"use strict";
/* Zhuonan Sun CSE154 AE HW6 8/8/2013
This program constructs a webpage which can perform 
different types of animations. You can also change the size of the image
and the speed of the animation.

This is my custom animation to be used by the overall program.
It was automatically generated by the StringMaker tool.
*/

var CUSTOM =
"\n" +
"     ___________\n" + 
"    /\\  /   \\  /\\\n" + 
"   / /\\/\\   /\\/\\ \\\n" + 
"  | |____| |____| | \n" + 
"  |  \\_./   \\._/  | \n" + 
" _|______ ^ ______|_\n" + 
"==|==== _____ ====|==\n" + 
"   \\\t         /\n" + 
"    \\           /\n" + 
"=====\n" + 
"      __     __ \n" + 
"     /\\/\\___/\\/\\ \n" + 
"    / __     __ \\\n" + 
"   / /  \\   /  \\ \\ \n" + 
"  | |----| |----| | \n" + 
"  |  \\_o/   \\o_/  |  \n" + 
" _|______ ^ ______|_ \n" + 
"==|==== _____ ====|==\n" + 
"   \\    \\___/\t /\n" + 
"    \\           /\n" + 
"=====\n" + 
"      /\\     /\\\n" + 
"     /  \\___/  \\\n" + 
"    / __     __ \\\n" + 
"   / /__\\   /__\\ \\\n" + 
"  | |    | |    | |\n" + 
"  |  \\_O/   \\O_/  | \n" + 
" _|______ ^ ______|_\n" + 
"==|==== _____ ====|==\n" + 
"   \\   |     |   /\n" + 
"    \\   \\___/   /\n" + 
"=====\n" + 
"      /\\     /\\\n" + 
"     /  \\___/  \\\n" + 
"    / __     __ \\\n" + 
"   / /  \\   /  \\ \\\n" + 
"  | |  O | | O  | |\n" + 
"  |  \\_ /   \\__/  | \n" + 
" _|______ ^ ______|_\n" + 
"==|==== _____ ====|==\n" + 
"   \\   /     \\   /\n" + 
"    \\  \\_____/  /\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
